name: sqfentity
author: HÃ¼seyin TOKPINAR <hhtokpinar@gmail.com>
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 

version: 1.4.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #sqflite_sqlcipher: ^1.0.0+6
  sqflite: ^1.3.0
  synchronized: ">=2.1.0+1 <3.0.0"
  path: ">=1.6.2 <2.0.0"
  sqfentity_gen: '>=1.4.0 <3.0.0'
  sqflite_common_ffi: ^1.0.0+2

dev_dependencies:
  build_runner: ^1.6.5
  build_verify: ^1.1.0
  

dependency_overrides:
  sqfentity_gen:
    path: ../sqfentity_gen        