name: sqfentity
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^2.0.0
  synchronized: ^3.0.0
  path: ^1.8.0
  
  sqfentity_gen: #'>=2.0.0 <3.0.0'
    git:
      ref: b5432a7ae44867ffa88178586aec83ddba0a4e92
      path: sqfentity_gen
      url: https://github.com/aynova-tecnologia/sqfEntity.git
  sqflite_common: ^2.0.0+2
  sqflite_common_ffi: ^2.0.0



# dependency_overrides:
#  sqfentity_gen:
#    path: ../sqfentity_gen