name: sqfentity
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 

version: 1.5.0

# environment:
#   sdk: ">=2.12.0-0 <3.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   synchronized: ">=2.1.0+1 <3.0.0"
#   path: ">=1.6.2 <2.0.0"
#   flutter_datetime_picker: ^1.5.1
#   sqfentity_gen: 

# dependency_overrides:
#   sqfentity_gen: 
#     path: sqfentity_gen      

    
# dev_dependencies:
#   build_runner: ^2.1.2
#   build_verify: ^2.0.0


environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  sqfentity_gen: 


dependency_overrides:
  sqfentity_gen: 
    path: sqfentity_gen
  build_runner: ^2.1.11
  build_verify: ^3.0.0

    
 
dev_dependencies:
  build_runner: ^2.1.11
  build_verify: ^3.0.0
  
    