name: points_of_sale
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  vibration: ^1.7.4-nullsafety.0
  shared_preferences: ^2.0.0-nullsafety.1
  package_info: ^0.4.3
  fluttertoast: ^8.0.1-nullsafety.0
  page_transition: ^2.0.1-nullsafety.0
  provider: ^5.0.0-nullsafety.5
  toggle_switch: ^0.1.9
  flutter_spinkit: ^5.0.0-nullsafety.0
  simple_animations: ^3.0.0-nullsafety.5
  animated_card: ^2.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  expandable: ^5.0.1
  get_it: ^6.0.0-nullsafety.2
  progress_state_button: "^1.0.3"
  sqflite: ^2.0.0-nullsafety.3
  lite_rolling_switch: ^0.1.1
  autocomplete_textfield: ^1.7.3
  rounded_loading_button: ^1.0.18
  path_provider: ^2.0.0-nullsafety.1
  fab_circular_menu: ^1.0.2
  splashscreen: ^1.3.5
  awesome_dialog: ^2.0.0-nullsafety.1
  flutter_styled_toast: ^2.0.0
  loading_indicator: ^2.0.1
  image_picker: ^0.7.2
  flutter_svg: ^0.21.0+1
  country_code_picker: ^2.0.1
  flutter_sim_country_code: ^0.1.0
  location: ^4.0.0-nullsafety.0
  flutter_slider_drawer: ^2.0.0
  sqfentity: ^2.0.0-nullsafety.0
  sqfentity_gen: ^2.0.0-nullsafety.0+11
  flutter_datetime_picker: ^1.5.1

dependency_overrides:
  sqfentity: 
    path: ../sqfentity
  sqfentity_gen: 
    path: ../sqfentity_gen     
    
dev_dependencies:
  build_runner: ^2.0.1
  build_verify: ^2.0.0
  # flutter_test:
  #   sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: "DIN Next LT Arabic"
    fonts:
      - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Bold-3.ttf
      - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Medium-3.ttf
      - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Regular-3.ttf
        style: normal
  - family: Almarai
    fonts:
      - asset: assets/fonts/Almarai-Regular.ttf
        weight: 100
  - family: "Bangers"
    fonts:
      - asset: assets/fonts/Bangers-Regular.ttf
        style: normal
  - family: "RedHatText"
    fonts:
      - asset: assets/fonts/RedHatText-Bold.ttf
      - asset: assets/fonts/RedHatText-Medium.ttf
        style: normal
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
